name: Metrics
on:
  # Schedule updates
  schedule: [{cron: "* * * * *"}]
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    if: "github.repository == 'Darakah/Darakah'"
    steps:

      # ======================================================================================
      # 🖼️ TEMPLATES
      # ======================================================================================

      # Classic template example
      - name: 📗 Classic template
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@master
        with:
          filename: metrics.classic.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: header, repositories
          plugin_lines: yes
          plugins_errors_fatal: ${{ github.repository == 'Darakah/Darakah' }}
          # use_prebuilt_image: master # ⚠️ DO NOT USE THIS OPTION, this is for pulling pre-built master image to make workflow faster 

