# See https://github.com/lowlighter/metrics for documentation
# This worflow is scheduled for every hour, and also run after each commit (GitHub action excluded) on master/main branch

name: Metrics
on:
  schedule:
    - {cron: "00 5 * * *"}
  push:
    branches:
      - master
      - main
  workflow_dispatch:
jobs:
  github-metrics-personal:
    runs-on: ubuntu-latest
    steps:

      - name: 🦑 Personal metrics
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.svg
          token: ${{ secrets.METRICS_TOKEN }} 
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: "header, repositories"
          plugin_lines: yes
          plugin_topics: yes
          plugin_topics_mode: mastered
          plugin_followup: yes
          plugin_habits: yes
          plugin_habits_from: 200
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          plugin_languages: yes
          plugin_languages_ignored: asp, html, tex, makefile, qmake, cmake, javascript
          # # # plugin_languages_skipped: lowlighter / tex, makefile,
          plugins_errors_fatal: yes
          plugin_stars: yes
          plugin_stars_limit: 3
          plugin_reactions: yes
          plugin_reactions_limit: 1000
          plugin_reactions_details: percentage
          plugin_starlists: yes
          plugin_starlists_limit_repositories: 3
          plugin_starlists_only: TC39
          plugin_discussions: yes
          plugin_discussions_categories_limit: 8
          plugin_achievements: yes
          # use_prebuilt_image: master
          config_timezone: America/New_York
